### ISSUE TITLE
Apollo 12 MCC2 PAD Bug

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#1056]
Hello

I'm doing apollo 12 for the first time. Everything has been going well as far as I know. I had my first MCC during the translunar coast (MCC2), and I noticed that the PAD data is incomplete. We don't have star, SFT, TRN values to check the CMS attitude for the MCC burning for example: here is a print:

https://i.imgur.com/kYVfF9o.jpeg

Anyway I had enough data for MCC2 and did the burn anyway. I'm hoping that everything can go well. If you need me to send a senario, let me know. Im with update 2115.

I just remembered (I'm editing this) that in Apollo's list of celestial bodies, 00 is a planet. If I use SFT and TRN with the PAD value (+00000 for both) the Earth is centered on the sextant. So perhaps everything is correct in the PAD.

Best regards

**Comment by indy91** [comment]
Sorry, I didn't get to look into this until now.

When the PAD shows zero for a sextant star then it just didn't find one at the burn attitude, not that it wants you to use some planet. This can happen if Earth, Moon or Sun are in the way of the star. Now, the logic to determine if one of these is blocking the star is too strict. It uses some equations from the AGC code which doesn't even allow stars that are 5° above the horizon. So even if you are far away from the Earth, there is a 5° ring around it where stars are not taken into account for sextant star checks. I have only very roughly checked your specific case, but the center of the sextant view (0° trunnion and shaft) is close to Earth, so this must be what is happening for you, just bad luck with the attitude.

I will leave this issue closed, but eventually there will be two improvements. The Maneuver PAD should show N/A instead of zero for the star data, which the Maneuver PAD in the RTCC MFD already does. And the RTCC logic will be less strict about using stars. I believe the real logic takes the atmosphere into account, but it would not discard as many stars as the current calculations do.

**Comment by RL77** [comment]
Thank you for your answer and explanation

I closed the issue because LOI-1 went really well yesterday, so I thought, that being the case there is no problem at all. It was not even necessary to do the MCC3 and/or 4.
So in this case, the star for alignment is behind the planet... very interesting. Here are my LOI-1 and LOI-2 pads. I'm going to do LOI-2 tonight:

https://i.imgur.com/3dKvlRx.jpeg

https://i.imgur.com/9lEYd31.jpeg 

If I see anything strange during the rest of the mission, I'll let you know.

**Comment by RL77** [comment]
Hi

Here is another situation that I think is the same issue, but this time with the plane change PAD:

https://i.imgur.com/uiIf7yf.png

https://i.imgur.com/CmeA3sr.jpeg 

Anyway, everything is going well, I made a beautiful landing, but a little far from Surveyor crater :D. I'm going to EVA 2 now, I'm enjoying this  a lot, as always!

https://i.imgur.com/t8wMXq5.jpeg

Regards
