### ISSUE TITLE
Cross-range (Latitude) error in P63/64 during LM lunar landing

### ISSUE THREAD

**Issue by jalexb88** [dseagrav/NASSP#350]
There seems to be an issue with the LGC's computed position during a lunar landing. The error is apparent after landing when comparing the LGC's idea of the position with P68, with the actual position displayed on an MFD such as PAMFD. In my tests I have noticed that while the downrange (longitude) error is almost nil, 0.01 or less, the latitude error is higher, about 0.04 degrees north of actual on average and sometimes higher. In my tests I have found the cause of this is the landing radar velocity updates that start when slowing through 2000 fps as per the padload and if I lower that to a very low value such as 600 fps, the error is pretty much gone. Another side-effect of this issue is if you perform an abort late during the landing, the lunar insertion plane will be off by as much as 0.3 degrees and that means the RR is unable to find and lock-on to the CSM.

**Comment by ggalfi** [comment]
Hi folks,

I silently accepted the challenge to find out what is going on here, but I was heavily engaged with my everyday work, so it took me a while to come to some conclusion. Anyway I think I found (at least one) cause of this deviation. I had the same observation as jalexb88 that attempting a landing without the landing radar, the lateral deviations are smaller (although the vertical error is certainly much larger), so the cause of the problem should be somewhere in the LR simulation (I assume that the Luminary code is practically perfect as it has proven its accuracy in real life six times). I carefully went through each step of the data flow of the LR, and the first suspicious thing I found was the  calculation of the antenna to NB transformation matrix, This matrix - or the two versions of this matrix corresponding to the two radar positions - are hardwired into the Luminary210 code and could be found in the CONTROLLED_CONSTANTS.agc under the name VXBEAMNB, VYBEAMNB, and VZBEAMNB. If you match this matrices with the formal expression in the NASSP source code and in the GSOP Sec5 document you will see that to get the same values as in the Luminary code for the pos1 matrix you should use alpha=-6 degs and beta=-24 degs - and not the positive values in the NASSP source! So I changed the positive values to the negative ones in lemsystems.cpp - and got a totally inoperable radar. I experimented with some combinations like alpha=-6 and beta=24, but still ended up in some botched landings (sidenote: this Charlie Duke guy should be a very generous man because he still called me "percy precision" even when I put down the Orion in the middle of the South Ray crater :) ). So I've looked further for  some bug and I finally  found it: when calculating the range beam coordinates in NB system, the range beam vector given in the antenna coordinates is multiplied with the transformation matrix from the right (through the tmul function) but it ought to be multiplied from the left (with the help of mul function). It is easy to see why the latter one is correct: if I have a vector given in antenna coordinates (like v_a)  then it could be written as a combination of the antenna system's unit vectors U_X, U__Y, U_Z as v_a=v_a.x * U_X+v_a.y  * U_Y+v_a.z * U_Z. To get v_a-s components in any other coordinate system you need U_X, U_Y and U_Z's coordinates expressed in that other system. In our case the other system is the NB and the expression for the U_X,Y,Z vectors in the NB system are the U_XAB, U_YAB, U_ZAB vectors. So to get U_RBA's components in NB, one should calculate U_RBB as U_RBA.x * U_XAB+U_RBA.y * U_YAB+U_RBA.z * U_ZAB=(U_XAB.x * U_RBA.x+U_YAB.x * U_RBA.y+U_ZAB.x * U_RBA.z, ..., ...) which is equivalent to multiply U_RBA with the matrix (U_XAB| U_YAB| U_ZAB)=_M(U_XAB.x, U_YAB.x, U_ZAB.x, U_XAB.y,....). There is a similar issue with the calculation of the velocities in antenna coordinates: certainly the inverse of  the above transformation is to be applied which for this type of matrix is simply a multiplication from right (or multiplication from the left with the transposed matrix), so tmul should be used here, but there is mul in the source code. With all these modifications the LR began to work flawlessy. To summarize my findings:
 - The Euler angles should be changed to negative values: alpha=-6.0 * RAD; beta = -antennaAngle * RAD;
 - for the  transformation of the beam from antenna to NB system mul should be used instead of tmul
 - for the  transformation of the rates from NB to antenna system tmul should be used instead of mul
 - bonus: there is an unnecessary cos calculation when the range is calculated. It is more efficient if we introduce a new variable cosang and do the calculation in this way:
      cosang = dotp(unit(-pos), unit(lrvec_glob));
      ang = acos(cosang);
      range = alt / cosang/0.3048;

I tried both Apollo 16 and 17 PDI with this new LR calculation (V57 is performed at exactly at 40000 feet) and had to following results:
Apollo 16
Map MFD: S8.97 E15.49
P68 Noun 43: -8.98 +15.52

Apollo 17
Map MFD: N20.19 E30.75
P68 Noun 43: +20.19 +30.77

So there is still a slight downrange error (700-800 meters) but I wouldn't blame the LR for that. I landed Apollo 16 with a very late V57 at 15000'  and got exactly the same result as above.
I attached the modified version of lemsystems.cpp if you would want to incorporate it into the main branch.
[lemsystems.zip](https://github.com/dseagrav/NASSP/files/2051832/lemsystems.zip)

**Comment by jalexb88** [comment]
Awesome work! I just tried it and made an Apollo 12 landing right next to surveyor 3 with those changes, made my night! Once Niklas gets an eye on this for sure we can integrate ASAP

**Comment by indy91** [comment]
The changes work very well for me as well. Latitude error is basically gone. In the Apollo 11 PDI Demo scenario the error at the landing site is 0.00° in latitude and 0.04° in longitude. In my old Apollo 15 testing scenario I did a state vector update and clock update right before PDI and the result was 0.00° off in latitude and only 0.01° in longitude. So I guess it's safe to say that the errors caused by any issues with our landing radar code have become close to 0. Thanks for figuring this out! I was never very good with coordinate system transformations...

**Comment by jalexb88** [comment]
After a lot of testing today I will call this one done and close the issue. Thanks again ggalfi!
