### ISSUE TITLE
Impossible to update REFSMMAT

### ISSUE THREAD

**Issue by Rikifire** [dseagrav/NASSP#37]
Orbiter crashes when trying to update REFSMMAT on PAMFD.

**Comment by indy91** [comment]
Can confirm. PAMFD can't actually calculate a REFSMMAT anyway, it just has two Apollo 11 REFSMMATs hardcoded. PAMFD will currently crash if you try the update with Apollo 10 or earlier and it will uplink a bad REFSMMAT (all zeros) for Apollo 12 or later.

You should be using the RTCC MFD to calculate and uplink various types of REFSMMATs. 

I'll either remove the REFSMMAT uplink in the PAMFD completely or at least include a check so that it doesn't crash for Apollo 10 and earlier.
