### ISSUE TITLE
Negative Perigee Value  for LOI 1 in the computer

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#400]
Hello,

I want to ask a question. I have already completed apollo 7 and 8 and now I am repeating 8 to practice a little more. I noticed for the second time that when I am doing the checklist for LOI1, that the perigee on the computer appears as a very different negative value from that displayed on the LOI 1 maneuver Pad. If I hit "PRO" on the computer and continue the checklist for the burning, I will end up in an orbit around the moon with a perigee with that same negative value, and the CSM will crash on the moon. I changed the value on the computer to the value of the correct perigee in the LOI1 Manuever Pad, and so the CSM was inserted into the correct orbit around the moon. I see that the remaining values of the manuever Pad appear correct on the computer, except for the perigee. Is this a problem or is supposed to appear like this, so that we have to change it for the correct value??

Thank you,

Best regards

**Comment by indy91** [comment]
I think the best way to approach this question is to explain what Program 30 does; and what it doesn't do. The only two inputs are the time of ignition (TIG) and the desired velocity change in three dimensions (DV). These are input on the first two displays of P30, Noun 33 and N81. After that P30 calculates the estimated apogee and perigee resulting from the burn. But these numbers are just a display and calculated from the TIG and DV, so changing them on N42 doesn't have any effect on the resulting burn at all.

Now, how does P30 calculate the apogee and perigee? The AGC doesn't have any routine for properly simulating a burn. So what it does is simply add the DV vector to the velocity of the spacecraft at the time of ignition. So an instantaneous velocity change at TIG. This will give a pretty accurate estimate for the apogee/perigee for short burns, like e.g. 5 seconds long. But a burn like LOI-1 that can be 5+ minutes long is a different story. There the DV is applied over a very period of time during which the spacecraft travels quite a long distance around the Moon. The input DV vector for this needs to be properly adjusted to take this travel into account. But because P30 simply adds the DV vector at TIG for the N42 estimates, the predicted orbit is very different from what actually will be achieved after the burn.

Because this can be confusing, some missions got both sets of numbers, the target apogee/perigee and what P30 will display. Here from the Apollo 11 transcript where the LOI-1 Maneuver PAD is read to the crew:

> 072:51:24 McCandless: LOI-1... 0169.2, plus 00610 [the actual resulting orbit] ... The values which you would see on Noun 42 prior to LOI burn are HA, plus 431.3; HP, minus 128.2. 

The actual numbers there will vary depending on the length in time of the LOI-1 burn. So in conclusion, for maneuvers that are several minutes long the display in P30 becomes inaccurate, this is normal and expected. And changing the values of N42 isn't necessary and also doesn't actually change the targeting of the burn.

**Comment by RL77** [comment]
Ok thanks for the explanation, it's was  only because  the first LOI that I did, I realy end up   in an orbit with negative perigee. I must have done something else wrong that time, thank you.

**Comment by indy91** [comment]
Yeah, could have had many causes. If you get anything like that in the future again we can try helping you out with it. Feel free to join us in the NASSP development and support IRC channel any time!
