### ISSUE TITLE
LM weigth and RCS

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#402]
Hello
I'm doing Apollo9  and I'd like to ask some questions. When we have to insert both CSM and LM weights for a burn, the weight of the LM is not in the Manuever Pad, so I have inserted  the weight of the CSM from the manuever pad ( in R1), and the weight of the LM that’s already in the computer display (in R2). Is this the correct procedure? I would also like to know if you can give me some advice regarding how to save fuel in RCS. I’m at GET 39h and my RCS A and C are getting close to half (+ - 60%, and B and D to + -70%). I have done the maneuvers in advance and slowly to save the fuel of the RCS, but with the LM attached, always spends a lot of fuel.
I registered on the site where we do the download of the new versions of NASSP (https://sourceforge.net/projects/nassp/) to be able to have support from there, but after signing in I cannot write in the "Support" section. Can you help me?
Thank you,
Best Regards

**Comment by indy91** [comment]
I don't think anyone from NASSP is looking much on Sourceforge these days. The best thing you can do for support is to register on the Orbiter Forum and open a new thread in the NASSP section (https://www.orbiter-forum.com/forumdisplay.php?f=102). That's also much better than opening an issue here on Github, that is really only meant for bugs and missing features, not questions.

Are you using the Orbiter 2016 release version? Then you will have trouble once you reach the docked burn of the DPS, because that is only working correctly in the more recent Beta versions of Orbiter. The reason for this is that Orbiter 2016 release version still calculated the properties of docked vessels wrong. The moments of inertial are way too high and I bet that is also causing your RCS trouble. When I first flew a mission with both CSM  and LM I had only 50% propellant left once I reached lunar orbit!

So NASSP switched to only supporting the Orbiter Beta for the NASSP 8.0 Alpha releases. You can get away with using Orbiter 2016 for most missions, but not Apollo 9. Here is the post I wrote when we switched to using the Orbiter Beta, should have the links you need to update: http://www.ibiblio.org/mscorbit/mscforum/index.php?topic=2925.msg26507#msg26507

**Comment by indy91** [comment]
Forgot to answer your first question. Yes, if the Maneuver PAD has no updated LM weight, just leave that as it is in V48.

**Comment by RL77** [comment]
hello

Thanks for the reply.Yes I am using the Orbiter 2016 released version. Tell me just one thing, I have to uninstall the 2016 orbiter for the beta, or can I run with the two?
From now on I just write here on Github to report bugs. I already have login to the orbiter forum too, but also in the Meadville Space Center. Can I ask questions in both or is it better in the orbiter forum?

I managed to do the missions of apollo7 and 8 in the orbiter 2016 released version, and according to what you said then it is also possible to do the 10 and 11 mission in the relesead version, except for 9, right?

**Comment by indy91** [comment]
You can run both in separate folders or simply install the Orbiter Beta in your current Orbiter 2016 folder.

Better use the Orbiter Forum. Because it was fairly unreliable and wasn't maintained anymore, we stopped using the Meadville Space Center and got us a subforum on the Orbiter Forum. But I still occasionally look there for new posts.

Yeah, Apollo 9 can't be fully done because the docked DPS leads to the stack spinning out of control. I do believe Apollo 10 and 11 are possible in Orbiter 2016, but I can't guarantee it anymore. LOI-1 could be a problem. And as I said, in any mission with both CSM and LM you will need more RCS than in the Orbiter Beta because of the changed behavior of docked vehicles.

**Comment by RL77** [comment]
Okay, thanks for the help. With all those problems its  better to do things in beta. I  already installed the Orbiter 2016Beta and seems to work fine, including my saves from apollo 9 :), so I can restart the 9 mission from the separation of the CSM from SIVB.
 See you in orbiter forum !!
