### ISSUE TITLE
AGC possible issue/bug in apollo9

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#405]
Hello

 After performing the first burn with the LEM in apollo 9 i forgot to report something that I think is a bug. According to the checklist, at the beginning of the burn  the AGC shows:

F 06 40

after the engine cut-off it should be:

F 16 40

but instead what happened was that the "16" appears as 06 flashing alternately with 97.

F (06/97) 40

https://puu.sh/BxUi2/745d10b5c2.png

Then if we continue the checklist and do:

V76E

F 16 85

Pro

What happens after we hit "Enter" is that the display stops blinking and stays:

F 06 40

and if then we hit "Pro", it stays the same, and then fails to complete the operation.

What I did next was just V37E00E, and I continued the mission.

If this is an issue, I have a save file  at this point, and I can send it if you want.

**Comment by indy91** [comment]
It's not a bug, it's the AGC reacting correctly to an engine failure. Look here in the checklist: https://history.nasa.gov/afj/ap12fj/pdf/a12_lm_g&n.pdf on PDF page 34. The flashing V97 means "perform engine fail procedure". You have a few options what do to when that happens, as you can see on that checklist page.

Just continuing on with the mission is probably not good, because something clearly isn't working right for you. An engine failure means the AGC hasn't detected enough thrust and cut off the engine early. If you also have a save file from before the burn then I would like to take a look at it. Maybe the propellant valves aren't open or something like that.

(Don't take this in a serious way): something like this would never be a NASSP bug anyway, so better complain to the MIT Instrumentation Lab because they wrote the AGC code, haha.

**Comment by RL77** [comment]
Hello,

Ok :), but the burn went down right to the end, and it was me that cut-off the engine. I also repeted the burn and the result was the same. Yes i have the file before (t-1min +-) and after the burn. Were you want  me to sent that to you? Do you think it could be because i had my joystick active during the burn?

**Comment by RL77** [comment]
And thanks for that Link!!

**Comment by indy91** [comment]
Oh, is this the docked DPS burn? Where you are supposed to cut off the engine manually at 3 seconds before auto shutdown, right?

In that case everything is working right. We just don't have the flown Apollo 9 checklist for this procedure. According to the document I linked, if you want to terminate the burn you should do this:

> (TERM) ENG ARM-OFF V34E

I guess the checklist in the Checklist MFD doesn't give this procedure yet. Probably should be added. And I don't need the scenario anymore.

**Comment by RL77** [comment]
Yes is the docked DPS burn! Ok thanks , thats good to hear, i will continue the mission then! Thanks . Just a quick question, im at the EVA (the one next to the DPS burn). I have opend the doors. For now,   is not possible to go out with the astronauts of the  ship, right?

**Comment by indy91** [comment]
No, EVAs are currently not supported. So the Apollo 9 EVA day is not much more than a giant waste of oxygen, haha.

**Comment by RL77** [comment]
ahah ok thanks!
