### ISSUE TITLE
Apollo 10 maneuvers PADS do not appear

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#413]
Hello

I am doing the apollo 10 mission (with Orbiter 2016 Beta, and NASSP-V8.0-Alpha-Orbiter2016-1334). Some situations regarding maneuvers PADS are not occurring. The TLI PAD went well, but the TLI + 90h PAD did not appear. After the TLI burn that apparently went well, and the extraction the LEM from the SIVB, the maneuver PAD for separation of the SIVB with the SPS burn also appeared ,and I did the burn successfully. Later it was time to the MCC1 burn correction. On + -GET 7:00 a “ready for uplink” occurred (in which I did the uplink!). But them at the time of MCC1 maneuver Pad   at Get 10h00, the maneuver PAD did not appeared (never  show up after that, the only PADs that are appearing is the Block data Pads), just gives a  message to inform that the MCC1 was scrubbed. This had already happened to me in Apollo 8. I even opened an issue here about that. Indy91 answered me, and said that could happen, that MCC burns are scrubbed if we are in a good trajectory. To verify this, in order to confirm if there is really no problem, he told me this:

“If you are playing around with the RTCC MFD anyway, then you might as well check the DV of the burns that were scrubbed for you. Here is the general procedure to calculate MCC-1 and MCC-2: Open RTCC MFD, click on Maneuver Targeting, then Translunar. Click once on MAN to get to the maneuver option number 2. Click on TIG and input the MCC-2 time of ignition. After a short iteration it should give you a maneuver solution. If the DV for that is below 5 ft/s then everything is good. If it is larger or it doesn't find a solution at all, then there is a problem. Burn getting scrubbed because something is going wrong, not because things are going great.”

In Apollo 8 my value was below 5ft /s, and I also was able to end the mission successfully! But this time in Apollo 10 shortly before MCC1 (GET10h) I did the same thing on the Apollo RTCC MFD and the value of dV was well above 5 ft / s (+ 27.0 ft/s) , so the MCC1 maneuver Pad should have appeared. I continued the mission and I'm in GET 19h32 with a value of dV 27.6ft/s as you can see these prints:

GET 10h00
https://puu.sh/C06ZD/b1c280b920.png
GET 19h32
https://puu.sh/C07i7/545349a8fb.png

Now I'm going to continue the mission until MCC2 burn, in which is already close in my present GET, but if the maneuver Pad for this burn does not show up, then I think something is definitively wrong with the Apollo 10 mission. Is this an issue/bug? 
Also something happened in the first in Cis-Lunar navigation. After marking the horizon (Far or near) we have to mark the star that is assigned to us in the flight plan/checklist. But the CSM most of the time gets placed in an attitude in which the LEM is blocking the star's sight. What I did was move the CSM (as I did on P52 on Apollo 9, but now this is different) so I could see the star, and then superimpose the star on the horizon with Slos "V" Key activated, but it's harder to get values of dR,dV below 50 after we mark the star, by doing this!! Doesn’t the mark on the star has to be made with the CSM in the attitude that he maneuverers automatically for Cis-Lunar? What I did, moving the CSM to see the star was correct? Or this also can be an issue / bug? Can you help with these two issues?

Thank you very much!

Best regards

**Comment by indy91** [comment]
-PADs in Earth orbit: The PADs for the TLI+90min and TLI+4h maneuvers would have appeared before the TLI PAD. Maybe you just missed them? It doesn't wait for you to write the PADs down, it will just display the next a few minutes after the last one. The TLI+90 one is being displayed fine in my older scenario; although that doesn't guarantee it's working in new ones of course.

-Uplink at 7h GET: That was for the PTC REFSMMAT, which the MCC should have told you about (by displaying "PTC REFSMMAT" as a status message).

-MCC-1 scrub/MCC-2 DV: This is an interesting topic actually. The first MCC after TLI will have a non-zero DV even in the nominal case for Apollo 10. In the Apollo 10 Flight Plan (page 3-12) it has a MCC-1 as large as 57 ft/s, although we usually don't get such a high DV. The reason is that the mission does a kind of plane change to get the lunar orbit orientation exactly the same as it will be on Apollo 11, even though the Earth-Moon geometry doesn't support that for TLI targeting. Not only did Apollo 10 fly exactly over the planned landing site for Apollo 11, but also from the same direction (approach azimuth). That's what this non-zero midcourse correction is for. So for the special trajectory of Apollo 10 getting a larger DV is totally normal.

They even increase the DV criterium to execute MCC-1, and as happened on the actual mission, MCC-1 was scrubbed even though it would have had a significant DV. MCC-2 definitely will have to be done in your case though. If it tries to scrub MCC-2, then something is wrong.

-Cis-lunar navigation attitude: The attitude that the CMC calculates in P23 is simply the shortest path from your current attitude to pointing the sextant in the right direction. So it doesn't consider that the LM might be in the way. During the actual mission MCC-H gave the astronauts a specific attitude to maneuver to, so that the LM won't be in the way. There probably will be something for this in the RTCC MFD or the MCC at some point. Right now you just have to roll the spacecraft around until the LM is out of the way. Then I usually let the CMC calculate the attitude again. This can take a while.

On later missions the CMC software became a bit smarter. Starting with Apollo 15 you had the option to do a 3-axis maneuver in P23 that will maneuver such that the spacrcraft is rolled 180° relative to the horizon. That will give a 180° shaft angle for the sextant and so the LM will never be in the way.

**Comment by RL77** [comment]
Hello,

Thank you very much for the explanation. By the way, I thought that dV may have a higher limit on this mission because of the separation of SIVB with SPS :). Meanwhile last night, I was able to reach MCC2 and the maneuver Pad appeared with a dVC of 27ft/s. And before that, the second Cis-Lunar navigation went very well, the LEM did not stand in front of any stars. I got excellent dR, dV values !! So I will continue the mission, and if I detect any anomalies I will  report to you! Regarding the manuveuver Pad TLI + 90, I now no longer know for sure if it was not the TLI + 4h that did not appear. Anyway, I might not have seen them, just like you said! 

Thanks Again!

**Comment by indy91** [comment]
The evasive maneuver with the SPS is compensated by overburning TLI by 2 m/s. The evasive burn is mostly in the direction of Earth, so that should cancel each other out. Not completely though, this procedure does make the necessary MCC DV larger.

The TLI+4h PAD on Apollo 10 and later wasn't a full Maneuver PAD actually, just a shorter form P37 PAD (https://history.nasa.gov/afj/ap10fj/pics/p37.jpg). Maybe easier to overlook.

**Comment by RL77** [comment]
Hello

Thanks again for the explanation. Since we are talking about problems with NASSP, there is a graphic problem that I wanted to report for some time, and I do not know if it is a NASSP problem, or my graphic card. First problem is in Kennedy Space Center on the launch pad, there is a large area that is always white. Only happens when we run NASSP, otherwise the KSC scenario is good, here is a print:

https://puu.sh/BWgeg/845ebe4e34.png

 we can even see it from space:

https://puu.sh/BWgqM/4ab65613fc.jpg

Then  other problem occurs in the separation of the stages of the Saturn V. When the separation of the 1st stage, 2st stage, and the CSM takes place, small particles are dispersed. But in my Orbiter 2016, these tiny particles are huge flakes, and they make a huge cloud. It does not make any difference to me in the separation of the 1st and 2nd stage, because the engine of the next stage ignites, and we simply move away from that cloud! But when we separate the CSM, it's different! Everything is enveloped in a huge cloud of flakes that disperse slowly, and the vision is blocked for a very long time until the flakes are gone. What I do in this situation, is immediately following the CSM separation, I make a save file, then I shut down Orbiter, and I reload that save file, and everything is fine after that, the flakes disappear. Here is a print right  after the separation of the CSM in the mission Apollo 10 that I am doing now:

https://puu.sh/BWXs3/fb9e9224b3.jpg

Interestingly, in Apollo 7, in the separation of the 1st stage (when I was in this mission) this problem of the flakes did not happen, but later it happened in the separation of the CSM. All  of this happens in Orbiter 2016, either is  release or in Beta version.

And also, I checked installing NASSP for the 2010 Orbiter, both problems of the white scenario and the flakes do not occur!

 My graphic card is a ASUS HD7770 series and I’m using windows 7 Pro, if it helps!

https://www.asus.com/Graphics-Cards/HD7770DC1GD5/

Is this my problem or just unfinished/issue graphic in NASSP?

Thanks!

**Comment by indy91** [comment]
It should definitely not look like that. Which graphics client for Orbiter are you using?

**Comment by RL77** [comment]
Unfortunately I am not the person with the most knowledge about these matters. Regarding the graphic client, I think you are referring to what is here in this link of the Orbiter website:

https://archive.codeplex.com/?p=d3d9client

If so, I just learned that this existed to install about 2 months ago, and the problems I mentioned have been around since I started with NASSP in the Orbiter 2016  (+ - May this year) way before I have installed the client. Anyway I notice this Graphic Client in the orbiter forum. I did download more than one version but I think the one I have installed is this:

D3D9ClientBeta25.3-forBETA r70(r908)

Or maybe this:

D3D9ClientBeta25.4-forBETA r71(r914)

I don’t remember.. :(

Also, I forgot to mention one important detail! I use the orbiter and fly the NASSP on a Desktop computer with the graphics card I mentioned earlier, but I also have the Orbiter 2016 (released version) installed on my Laptop computer with NASSP! The problems are the same. This Laptop computer has an onboard graphics card (Intel HD Graphics 4000), lower than the card I have on the Desktop computer. The windows are the same on both computers (W7 Pro) . Here are some prints from Laptop computer:

Apollo 9 quick launch from NASSP training save files.

The White area:

https://puu.sh/C1keO/dc7a9a9303.png

https://puu.sh/C1khf/431185ae70.png

https://puu.sh/C1ki1/b72d71c0be.png

https://puu.sh/C1kk9/d0f60a3494.png

And 1º stage separation and the huge flakes:

https://puu.sh/C1kls/30513b0bd5.png

https://puu.sh/C1klB/778cd29b70.png

It is strange to occur on two PCs with different boards.Maybe i have some software problem on both PCs!  In the Desktop computer for example, I have installed Flight Simulator, with scenario addons, detailed aircraft (PMDG, Aerosoft, etc), weather engine, ATC Network programs (VATSIM, IVAO), and not I have no graphics problems. Anyway this is more just for you to know. I can go around to the problem of the flakes  anyway. But of course it would be better if these problems did not exist. Thanks!

**Comment by indy91** [comment]
I first thought it might be missing textures, but that shouldn't be the case with the Orbiter 2016 release version. Have you installed any other textures in addition to the ones that come with Orbiter 2016? The old high-res Earth and KSC textures from this post (http://nassp.sourceforge.net/wiki/Installation) don't apply anymore.

About the DX9 Client, if you are using the latest Orbiter Beta then you also need the DX9 Client that is specifically for that version. Right now the Orbiter Beta is on release 84, so you will need the "D3D9ClientBeta28.0-forBETA r84(r996M)" file from this post: https://www.orbiter-forum.com/showthread.php?p=582991&postcount=4609 Look at that, the DX9 Client releases are even less accessible than the NASSP 8.0 Alpha release :D

Also, I am not sure you are actually using the DX9 Client. Are you using the Orbiter_ng.exe to start Orbiter instead of the Orbiter.exe? The Orbiter.exe can only use the default (DirectX 7) graphics client. This might explain the weird particle effect, it might not be super compatible with the old client.

**Comment by RL77** [comment]
It's solved !! : D
Yes I have the latest version of the  orbiter 2016 Beta , and I installed the client that you told me, and I ran the orbiter from the Orbiter_ng.exe file. Configurations of orbiter again, and it was done:

https://puu.sh/C1OUi/6c6e8a2da2.jpg

https://puu.sh/C1OUW/42d7124686.jpg

https://puu.sh/C1OXr/f7bdea9368.jpg

https://puu.sh/C1OZu/c10d47d51e.jpg

https://puu.sh/C1OZU/b5357af7a0.jpg

absolutely beautiful!! :D :D :D Thanks  a Lot !!

What are the correct high resolution textures to install in Orbiter 2016 Beta? :)

Here?

https://puu.sh/C1R9X/50cde63195.png

https://puu.sh/C1Rbu/5775ab9a84.png

Best regards

**Comment by indy91** [comment]
Yeah, I think those are the ones to download. They are gigantic files though and need a decent computer, so I wouldn't recommend it for your laptop.

**Comment by RL77** [comment]
I'm going to install it on the Desktop computer, and see if it works !

thanks!
