### ISSUE TITLE
Apollo 10 Missing Pads and State vector Uplinks

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#438]
Happy new year! I finally mannage to do the docking with the LM in apollo 10 :)

https://puu.sh/CpxzZ/a5459f5432.jpg

https://puu.sh/CpTL0/e2069da616.jpg

Then I separated the LM from the CSM, and I got to GET+-121h20min. During the time between the separation of the LM and my present GET, no PADs (MAPs; TEI) or state vector uplinks that were marked in the checklist appeared. The last Map Update is REV 22, and none of the TEI pads except the first one after LEM docking appeared. I have done the State vector uplinks so far, with the Apollo RTTCMFD. Will the TEI PAD for GET+- 139h, which is planned for apollo 10 will appear?

https://puu.sh/CqjRt/f56b7c7690.png

I also have another problem. In my present GET (121h20), I have to start P22 Orbital navigation. The orbiter 2016 Beta does not show the landmarks we need to mark on P22 (CP-1, CP-2, F-1)!

https://puu.sh/CqjOI/aa007cdbe9.png

https://puu.sh/CqjPj/06ec71c896.png

Just shows the Apollo landing sites!

https://puu.sh/CqjQ2/ea99ded951.png

I never noticed this because when I did the P22 on apollo 8, I was still using the Orbiter 2016 released version, in which I checked again, and the landmarks appear. But in Orbiter 2016 Beta the landmarks do not appear in any scenario. I've been looking for the location of the landmarks file, and found it here:

https://puu.sh/CqjWm/2bf60be507.png

The problem must be here I think! I even tried switching the "Moon" folder of the 2016 Beta Orbiter, for the “Moon” folder of Orbiter 2016 released version, but it made the situation even worse. So I went back for the original folder in Orbiter Beta. The missing PADS and uplinks are an issue? And the landmarks? Could it be due to some additional configuration in the Orbiter 2016 Beta that I do not know about? Can you help me?

Thank you!

**Comment by indy91** [comment]
The format of the landmark markers has changed and we don't have a file in the new format yet. The new format will support elevation for the landmarks, which is of course important in Orbiter 2016. The old format just had latitude and longitude. With the high-res textures for the Moon you can (with difficulty) do landmark tracking without the markers, after some careful map studying.

There are no missing PADs, somehow the mission sequence got messed up and you aren't getting the next scheduled update, nor will you get any others. What is the MCC state in your current scenario? In the CAPCOM Menu choose "9: Debug Options" and then "3: Report State". Also, can you check in the scenario file itself and search for "MCC_MoonRev" and "MCC_MoonRevTime". I'll add this to the numbers displayed with "report state" in the future, it's used quite often.

After the rev 22 map update you should be getting the one for rev 23, the logic for that is

`MoonRev >= 22 && MoonRevTime > 55.0*60.0`

So in your 22nd orbit around the Moon, 55 minutes after passing the backside of the Moon (180° longitude). That would be around 118:20h per the flight plan, but can of course vary.

If I remember correctly you aren't the first person to get this issue at this exact point in the MCC supported Apollo 10 mission, so there probably is something buggy which I can't easily see.

**Comment by indy91** [comment]
Increasing and decreasing states is mostly meant for debugging and in some cases it could lead to CTDs. And the states aren't always numbered consecutively, which is the case here. Your mission state is 231, but that state isn't used. Because it's a new day with the landmark tracking and to leave some space for potential additions on the rendezvous day the mission state jumps from 227 (starts at the rev 22 map update) directly to 300 (rev 23 map update).

So if you have manually incremented the mission state from 227 to 228 or later it will never jump on its own to 300, because it doesn't check the condition to jump from 227 to 300 anymore.

What you can do is go back to a scenario shortly before the rev 23 map update (118:20h or earlier), one with the rev 22 map update as the current PAD. And in that scenario the mission state should be 227, but I guess it's beyond that in your case. So just change it to 227 and the rev 23 map update should appear at 118:20h or up to half an hour later (the usual delay caused by entering lunar orbit too early). From there on it should all work properly again.

**Comment by RL77** [comment]
Ok I'll try this as soon as I can, then I'll tell you if it went well or not.

Thanks
