### ISSUE TITLE
Apollo 10 GDC align after TEI

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#446]
Hello,

I have done TEI for Apollo 10, and apparently it went well, it seems to be on a good trajectory. Shortly after came the first P52. After that I went to do the GDC align, and for some reason, I can not align, no matter how much times I repeat the alignment. I tried to repeat P52 thinking that it could have gone wrong, but I've  repeat  more than once (even in different attitudes so the AGC give me different stars), but the result is the same, it does not align. This is the first time this has happened to me! If you select FDAY 1/2 it shows:

https://puu.sh/CsFiQ/248f151563.png

If you select FDAY 2 it supposedly shows the correct attitude:

https://puu.sh/CsFij/551ad01782.png

So I'm just using FDAY 1:

https://puu.sh/CsFhM/2fb46a6154.png

Of course later when I started the PTC the CSM it was guided by the FDAY 1, which has the new orientation previously given by P52. It seems to be working fine anyway.. is it something I did wrong,  something new that I do not know, or is it some issue?

Thanks

**Comment by indy91** [comment]
Yeah, I recently did an extensive overhaul of the SCS with many changes to the GDC as well. In your screenshots I see that the FDAI Source switch is in CMC, not Att Set. It has to be in Att Set for GDC align to work. This is just a quirk of how the GDC operates and in NASSP this has only been necessary since the changes I did in the past few weeks. Does it work with that switch in Att Set?

**Comment by RL77** [comment]
Yes I noticed that recently there was a change. After an update I did recently, when I loaded my save file, I noticed a sort of reorientation in FDAY. You mean if I did the alignment with the FDAI Source switch in Att Set? Yes, I always do so, in fact it is a procedure I can do without the check list, as well as some other small procedures. I've even gotten the alignment done out of checklist plan a few times. 

Reviewing, the procedure is:

FDAY Select from 1/2 to 1 
FDAY Source to Att Set 
Scroll needles to FDAY attitude (With Att Set to GDC)
Att Set to IMU
Scroll needles to FDAY attitude to null FDAY errors
Att Set to GDC and push GDC align button
FDAY Source to CMC
FDAY Select to 1/2 again

This is how I always do. Or do you mean if after doing the alignment I must now keep FDAI Source switch in Att Set, so the two FDAYs show the new orientation correctly and aligned? I can try the alignment again when I get home, and I can send you some save files if you think is necessary. 

Thanks

**Comment by indy91** [comment]
The reorientation of the FDAIs is caused by moving the source of the attitude information to a different subsystem in NASSP. That will happen just once in older scenarios, then it gets saved/loaded correctly again.

Your procedure looks correct. Another change to the GDC is that you have to keep GDC align pressed for a little bit, but even a very short press of it should at least change the GDC attitude, just not necessarily to the final state. So yeah, at this point, I'll probably have to look at your save file to see what the issue is. GDC align works fine for me with the most recent NASSP version.

**Comment by indy91** [comment]
Maybe I misunderstood your first comment. Does GDC Align do anything or just the wrong thing? Also make sure you don't have the ORDEAL running anymore.

**Comment by RL77** [comment]
Yes I noticed that after making a save file, it was fixed. The GDC alignment does nothing, and I'm sure the ORDEAL is off. That change to the GDC that you have to keep GDC aligned pressed for a little bit, must be where  my problem is! I just did a quick press as always. As soon as I can, I'll repeat the alignment, and keep GDC aligned for a little bit, to see how it goes. Then i will report back to you.

Thanks!

**Comment by RL77** [comment]
It's solved! It was the GDC align. I pressed and hold for a little bit, and got lined up.

https://puu.sh/Ct4A2/65c4640d5b.png

 We can  see the needles moving as we press and hold the GDC align Button. When they stop, it's aligned!

Thank you very much!

**Comment by indy91** [comment]
Yep, the thing with the needles is a very nice feature so that you know that GDC align is done. GDC align now works exactly as in the real SCS, it's driven by an attitude difference between the GDC attitude and the ASCP setting. This is supplied as a sort of attitude rate to the GDC, which is why the GDC align doesn't happen instantly anymore. I'm glad that the solution was this simple!
