### ISSUE TITLE
Cabin ambience volume

### ISSUE THREAD

**Issue by ThymoNL** [dseagrav/NASSP#641]
Some people have indicated that they experience the cabin sounds to be too loud for comfort, especially when using the simulator for extended periods.  Currently the volume of things like the cabin fans and suit compressors are fixed.

Too alleviate some headaches and to make the experience more enjoyable a volume control should be added to the PA configurator allowing users to adjust the equipment volume to a comfortable level.

**Comment by CaptainSwag101** [comment]
I would like to bump this issue because I agree that especially in the CM, the ambient noise is rather unpleasant when systems are configured per usual mission parameters (Suit Compressor on, and both Cabin Fans active).

First and foremost, I think the suit compressor sound should be attenuated if possible. Since the compressor is likely behind several panels deeper within the CM, the high-pitched whine it makes should be less audible than the sound of the circulating air. I don't know if it's possible to adjust the parameters of OrbiterSound to apply something like a low-pass filter, but if not, I have personally achieved a similar effect by putting the original WAV sound file in Audacity, applying a 1000 Hz low-pass filter with -12 dB rolloff, and then amplifying by 2 dB. This results in the lower-pitched sound of rushing air to remain mostly the same volume, while muffling the high-pitched whine of the compressor to a much more tolerable level, while not eliminating it entirely. This on its own makes the cabin ambience far less grating on the ears, in my subjective opinion. To take things further, the cabin fan volume could optionally be reduced slightly (or the astronaut could use only one cabin fan, but that would deviate from normal mission parameters), but the suit compressor sound is probably the primary culprit for uncomfortable listening.

For your consideration, here is a copy of the altered suit compressor sound effect WAV file.
[suitcompr_muffled.zip](https://github.com/orbiternassp/NASSP/files/8234916/suitcompr_muffled.zip)

**Comment by n7275** [comment]
can this be closed?
